# x1, x2; y1, y2; z1, z2: int range for elements that force is applied to
# F_x, F_y, F_z: the values of the 3D force vector applied to elements in range (Newtons)

force_field_0:
  x1: 0
  x2: 1
  y1: 0
  y2: 1
  z1: 0
  z2: 1
  F_x: 0
  F_y: 0
  F_z: 0

force_field_1:
  x1: 0
  x2: 20
  y1: 0
  y2: 16
  z1: 38
  z2: 39
  F_x: 0
  F_y: 1000
  F_z: 0