# x1, x2; y1, y2; z1, z2: int range for elements that force is applied to (all inclusive)
# F_x, F_y, F_z: the values of the 3D force vector applied to elements in range (Newtons)

force_field_1:
  x1: 11
  x2: 12
  y1: 3
  y2: 4
  z1: 3
  z2: 4
  F_x: 1
  F_y: 0
  F_z: 0