# E_x, E_z, E_y: Young's moduli (Pa)
# nu_xy, nu_yz, nu_zx: Poisson's ratioes (m/m)
# G_xy, G_yz, G_zx: Shear moduli (Pa)

pla_anisotropic:
  # FDM PLA with layer lines (X) perpendicular to pull (Y)
  # Weakest: Y (perpendicular to layer lines), 2nd: Z (through-layer), Strongest: X (along fibers)
  # Orthotropic mechanical properties of PLA materials fabricated by fused deposition modeling, Li et al.
  # not given values estimated
  E_x: 2.669e9
  E_y: 2.583e9
  E_z: 2.208e9
  G_xy: 0.919e9
  G_yz: 0.8e9 # estimated
  G_zx: 0.844e9
  nu_xy: 0.43
  nu_yz: 0.34 # estimated
  nu_zx: 0.306

pla_isotropic:
  # Averaged values from aniso PLA
  E_x: 2.487e9
  E_y: 2.487e9
  E_z: 2.487e9
  G_xy: 0.915e9
  G_yz: 0.915e9
  G_zx: 0.915e9
  nu_xy: 0.36
  nu_yz: 0.36
  nu_zx: 0.36

pla_xanisotropic:
  #exaggerated anisotropic PLA values for testing
  E_x: 2.669e9
  E_y: 1e9
  E_z: 3e8
  G_xy: 0.919e9
  G_yz: 0.6e9 # estimated
  G_zx: 0.75e9
  nu_xy: 0.43
  nu_yz: 0.34 # estimated
  nu_zx: 0.306

aluminum_5052_h32:
  # TODO get accurate values 
  E_x: 70e9
  E_y: 70e9
  E_z: 70e9
  G_xy: 26e9
  G_yz: 26e9
  G_zx: 26e9
  nu_xy: 0.33
  nu_yz: 0.33
  nu_zx: 0.33