# E_x, E_z, E_y: Young's moduli (Pa)
# nu_xy, nu_yz, nu_zx: Poisson's ratioes
# G_xy, G_yz, G_zx: Shear moduli (Pa)

pla: # TODO get accurate values
  sigma_yield: 30e6
  E_x: 45e6
  E_z: 25e6
  G_xy: 40e6
  G_zx: 25e6
  nu_xy: 0.36
  nu_zx: 0.36

steel: # TODO get accurate values
  sigma_yield: 215e6
  E_x: 200000e6
  G_xy: 77000e6
  nu_xy: 0.3