# x1, x2; y1, y2; z1, z2: int range for nodes whose displacements will be measured

displacement_range_0:
  x1: 0
  x2: 0
  y1: 0
  y2: 0
  z1: 0
  z2: 0

displacement_range_2:
  x1: 47
  x2: 48
  y1: 0
  y2: 19
  z1: 1
  z2: 2

displacement_range_tensile_pull:
  x1: 0
  x2: 8
  y1: 79
  y2: 80
  z1: 0
  z2: 1