# x1, x2; y1, y2; z1, z2: int range for elements that are set at density = 1 (for interfacing with testing equipment)

protected_zone_0:
  x1: 0
  x2: 1
  y1: 0
  y2: 1
  z1: 0
  z2: 1

protected_zone_1:
  x1: 0
  x2: 20
  y1: 0
  y2: 16
  z1: 0
  z2: 3