# x1, x2; y1, y2; z1, z2: int range for elements that are set at density = 1 (for interfacing with testing equipment)

protected_zone_0:
  x1: 0
  x2: 1
  y1: 0
  y2: 1
  z1: 0
  z2: 1

# Protected extra space on support side: 20 elements in y for 45x145x6 tensile setup
tensile_support_face:
  x1: 0
  x2: 30
  y1: 0
  y2: 35
  z1: 0
  z2: 4

# Protected extra space on load side: 20 elements in y for 45x145x6 tensile setup
tensile_load_face:
  x1: 0
  x2: 30
  y1: 105
  y2: 140
  z1: 0
  z2: 4

cantilever_support_face:
  x1: 0
  x2: 20
  y1: 0
  y2: 20
  z1: 0
  z2: 10

cantilever_load_face:
  x1: 15
  x2: 20
  y1: 0
  y2: 20
  z1: 50
  z2: 60

