# x1, x2; y1, y2; z1, z2: int range for elements that are fixed

support_mask_0:
  x1: 0
  x2: 1
  y1: 0
  y2: 1
  z1: 0
  z2: 1

tensile_test:
  x1: 0
  x2: 30
  y1: 0
  y2: 1
  z1: 0
  z2: 4

cantilever_test:
  x1: 0
  x2: 20
  y1: 0
  y2: 20
  z1: 0
  z2: 1

debug_support_mask_50x50x2:
  x1: 0
  x2: 50
  y1: 0
  y2: 3
  z1: 0
  z2: 2

debug_support_mask_75x75x1:
  x1: 0   
  x2: 75
  y1: 0
  y2: 3
  z1: 0
  z2: 1